/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import com.google.gson.Gson;


public class App {
    public String getGreeting() {
        return "git push --set-upstream origin mainHello World!";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        try
        {
            istatic Gson gson = new Gson();  // create gson instance
            Reader reader = Files.newBufferedReader(Paths.get("recentquotes.json")); //create a reader ?
        }
        catch (Exception )
        ArrayList<Quote> quotes = new ArrayList<>();
        Quote  quote = new Quote();

        String newQuote = gson.fromJson(quote.text);


    }
}
