/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;


public class App {
    public String getGreeting() {
        return "git push --set-upstream origin mainHello World!";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        try
        {
            Gson gson = new Gson();  // create gson instance
            Reader reader = Files.newBufferedReader(Paths.get("./app/src/main/resources/recentquotes.json")); //create a reader ?

            Quote[] allQuotes = gson.fromJson(reader, Quote[].class);
            QuoteLib quotesLibrary = new QuoteLib(allQuotes);
            System.out.println("moving on");
//            for(Quote qt : allQuotes){
//                System.out.println(qt.text);
//            }

//            Quote  quote = new Quote();
//            String newQuote = gson.fromJson(quote.text);
        }
        catch (Exception ex){
            ex.printStackTrace();
        }

    }
}
